---
- name: apt updated
  apt:
    update_cache: yes
  when: "'debian' in group_names"

- name: apt upgrade
  apt:
    name: "*"
    state: present
  when: "'debian' in group_names"

- name: dnf update
  dnf:
    name: "*"
    state: present
  when: "'rhel' in group_names"

- name: brew update
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: "'macos' in group_names"
