---
- name: apt updated
  apt:
    update_cache: yes
  when: ansible_group is debian

- name: apt upgrade
  apt:
    name: "*"
    state: present
  when: ansible_group is debian

- name: dnf update
  dnf:
    name: "*"
    state: present
  when: ansible_group is rhel

- name: brew update
  homebrew:
    update_homebrew: yes
    upgrade_all: yes
  when: ansible_group is macos
