---
- name: check installing Command Line tools
  command: '/bin/bash -lc xcode-select --print-path'
  become: no
  register: which_cmd_cli
  changed_when: false

- name: check installing brew
  command: '/bin/bash -lc which brew'
  become: no
  register: which_cli
  ignore_errors: true
  changed_when: false

- name: install Command Line tools
  shell: |
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
    PROD=$(softwareupdate -l |
      grep "\*.*Command Line" |
      head -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
    softwareupdate -i "$PROD" -v;
    exit 0
  become: yes
  when: which_cmd_cli.rc != 0

- name: install Homebrew
  shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
  become: no
  when: which_brew.rc != 0
